version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./
    container_name: frontend
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000/api
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend